### ISSUE TITLE
Some questions about page track implementation.

### ISSUE THREAD

**Issue by silver-airship** [sev-step/sev-step#6]
From my current understanding, `slot->arch.gfn_track[mode][index]` is a counter similar to the COW mechanism, and accesses to it when it is greater than 0 trigger the NPF.
1. Am I understanding the mechanism correctly?
2. Who checks the value of the counter when an actual access(e.g. read access) to the tracked page occurs?
3. Has the SPTE of the tracked page been modified?Has the NPF handler been modified?
4. After I use track_all_pages() and catch the event, do I need to call track_all_pages() again?

**Comment by its-luca** [comment]
> From my current understanding, `slot->arch.gfn_track[mode][index]` is a counter similar to the COW mechanism, and accesses to it when it is greater than 0 trigger the NPF.
> 
> 1. Am I understanding the mechanism correctly?

`slot->arch.gfn_track[mode][index]` is only a metadata structure that logs that the given page has been tracked. Modifying this value will not trigger any page faults. 

> 2. Who checks the value of the counter when an actual access(e.g. read access) to the tracked page occurs?

I'd have to look that up. However, as stated above this is not important for the page fault tracking in SEV-Step

> 3. Has the SPTE of the tracked page been modified?Has the NPF handler been modified?

If you follow the the call to `kvm_mmu_slot_gfn_protect` in `kvm_slot_page_track_add_page` ( arch/x86/kvm/mmu/page_track.c), you will eventually get to the actual PTE update code which is located in `spte_protect` (arch/x86/kvm/mmu/mmu.c).

Yes, the NPF handler (`page_fault_handle_page_track`) has been modified, to send the page fault events to user space.

If you want to find all places changed by SEV-Step, simply produce a git diff against the c4daeffce56eebb52ec70ec59a202b879cd1c4fc commit in the kernel repo.

> 4. After I use track_all_pages() and catch the event, do I need to call track_all_pages() again?

If you want to get notified for the next access to the page corresponding to the current event, you need to track it again. You can use [track_page](https://github.com/sev-step/sev-step-userland/blob/9cdd98d98e322e45f22e3e35b0aa92df35bca6da/sev-step-lib/sev_step_api.h#L112) to only re-track that single page. However, you cannot immediately re-track the page, otherwise the VM would not make any progress and you would loop forever on the same page fault.   See, e.g. [test_pagetrack](https://github.com/sev-step/sev-step-userland/blob/9cdd98d98e322e45f22e3e35b0aa92df35bca6da/end2end-tests/host-client/pagetracking_tests.h#L12) for an example how to implement re-tracking.

**Comment by silver-airship** [comment]
Thank you for your patience in responding. For question 2, in x86 architecture, the page walk process after the TLB miss is completely performed by the hardware. the OS is only responsible for maintaining the page table. So I think the answer is hardware logic.
